### ISSUE TITLE
feature: extend to fonts? 

### ISSUE THREAD

**Issue by Rydwxz** [folke/styler.nvim#10]
### Did you check the docs?

- [X] I have read all the styler.nvim docs

### Is your feature request related to a problem? Please describe.

Changing colorthemes is a powerful way to keep my thoughts organized. Fonts would go one or two steps further towards immersion.

### Describe the solution you'd like

I understand that terminal-based nvim does not choose or display it's own font, but is there any way lua code can make a call out to the terminal emulator and request a font change, or a vim command to do so?

### Describe alternatives you've considered

Even without this feature, this plugin is a gamechanger for me, thanks so much man!

**Comment by folke** [comment]
I'm not planning to add this functionality to styler, but check my https://github.com/folke/zen-mode.nvim plugin to see how you could do what you want to achieve

**Comment by Rydwxz** [comment]
Cool, I very well may end up using that as I already use tmux!
