### ISSUE TITLE
FR: Also consider whether the system is in dark/light mode

### ISSUE THREAD

**Issue by chrisgrieser** [folke/styler.nvim#2]
Thanks for (yet another) plugin!

I have been using the [auto-dark-mode plugin](https://github.com/f-person/auto-dark-mode.nvim) for a while, and I fear getting those two plugins to play nice with each other is gonna be a bit tricky... 

I assume sherlocking the auto-dark-mode functionality within this plugin might be the cleanest solution?

**Comment by folke** [comment]
Just change the colorscheme and call `setup` again with a diffrent set of colorschemes in the auto dark mode plugin callbacks.

**Comment by chrisgrieser** [comment]
oh right, haven't thought of this. Well, that was easier than expected 🤦‍♂️ 
Thanks!
