### ISSUE TITLE
cannot select filetypes with a `-` in them

### ISSUE THREAD

**Issue by darburgess** [folke/styler.nvim#3]
Hello,

I am trying to set the colorscheme for neo-tree filetypes but it throws an error when I try to set the filetype properly.

Here is my styler config:
`require("styler").setup({
	themes = {
		neorg = { colorscheme = "tokyonight-night", background = "dark" },
		help = { colorscheme = "catppuccin-mocha", background = "dark" },
		dashboard = { colorscheme = "tokyonight-night" },
		lua = { colorscheme = "catppuccin" },
		neo-tree = {colorscheme = "catppuccin"},
	},
    })
`

Thanks in-advance, I might just need to escape the dash somehow?

**Comment by folke** [comment]
it would be helpful to tell me the actual error?

**Comment by folke** [comment]
Dashes work for me.

```lua

      require("styler").setup({
        themes = {
          markdown = { colorscheme = "tokyonight-storm" },
          help = { colorscheme = "gruvbox", background = "dark" },
          -- noice = { colorscheme = "gruvbox", background = "dark" },
        },
      })
```

**Comment by folke** [comment]
I see now you have a Lua syntax error in your code. It should be `["neo-tree"] = `

**Comment by ca-mantis-shrimp** [comment]
This did indeed fix it thank you
