### ISSUE TITLE
Enhancement: Command Sensitivity

### ISSUE THREAD

**Issue by rgnkn** [folke/styler.nvim#5]
I have this plugin called `ZenMode` of an unknown developer 😜 and I'd like to add a specific colorscheme to this. 

As this doesn't define a `filetype` I can't use `styler.nvim` to achieve my goal - unless you can direct me how to do this.

Therefore, I'd like to ask you whether it might be possible to extend this plugin to be also `command sensitive` (here the `:ZenMode` command, but this might also be interesting for some other commands).

**Comment by folke** [comment]
Maybe use the zen-mode `on_open` function and do `Styler colorscheme` in there?

**Comment by rgnkn** [comment]
I just checked. There are 3 problems with this, as I was able to find out:

1.) The colorscheme gets changed but `:colorscheme` doesn't be aware of this change.

2.) The colorscheme doesn't switch back when returning from `ZenMode`. Yes, I could use `on_close` for this, but this break the main point of using `styler.nvim`.

3.) It wouldn't be possible to define all settings for `styler.nvim` at one position in code.

So, from my point this solution doesn't work. If you find this idea (`command sensitivity`) interesting or usefull, you might want to think about implementing this feature.

Otherwise, feel free to close this issue.

BTW: Thx for all your useful plugins.

**Comment by Normanras** [comment]
I'll add to this enhancement as it is adjacently related, but I'd love to have a different color scheme for when I open the terminal within Neovim! I tried a few different words in my `styler.lua`, but none of them worked with the plugin. This is a fantastic plugin for doing full stack work, but having a different color for my terminal would be chef's kiss! Thanks, Folke!

**Comment by folke** [comment]
@Normanras the terminal colors are actually not driven by highlight groups.

Most themes also configure them, but you can easily do that yourself.

Check the Neovim docs for `terminal-config`.

> The `{g,b}:terminal_color_x` variables control the terminal color palette,
where `x` is the color index between 0 and 15 inclusive.  The variables are
read during |TermOpen|. The value must be a color name or hexadecimal string.

**Comment by Normanras** [comment]
Interesting - didn't know terminal didn't interface with highlights! Thanks for the tip.
