### ISSUE TITLE
How to disable backgrounds?

### ISSUE THREAD

**Issue by opossalite** [folke/styler.nvim#7]
### Did you check the docs?

- [X] I have read all the styler.nvim docs

### Is your feature request related to a problem? Please describe.

Usually I can run commands like
```
    vim.api.nvim_set_hl(0, "Normal", {bg = "none"})
    vim.api.nvim_set_hl(0, "NormalFloat", {bg = "none"})
```
and this will disable all backgrounds and make it transparent. However with this plugin, I'm not sure how to run these commands in such a way that they affect all files.

### Describe the solution you'd like

If there isn't a way to do this currently, I guess I'd like to request a way to do this. I just want to get that fully transparent background.

### Describe alternatives you've considered

I'm fairly inexperienced with deep neovim configuration, and mostly piece together what I find on dotfile examples and forums. I've attempted to create autocmd's that run the commands but no to avail. Simply running the two commands in the colors.lua file does seem to have an effect, but only on files who haven't had a theme assigned to them in styler. Any filetype specified in styler will have the theme's default background color enabled.

**Comment by Rydwxz** [comment]
Hi,
Just adding that I came here to ask a similar question. Some sort of support for automatic transparency would be wonderful! I have forked this project and am trying to incorporate code from xiyaowong/transparent.nvim but have not got it to work yet.
